USE [master]
GO
/****** Object:  Database [YourDbName]    Script Date: 01/12/2023 18:09:44 ******/
CREATE DATABASE [YourDbName]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'YourDbName-Copy', FILENAME = N'TODO\YourDbName-Copy.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'YourDbName-Copy_log', FILENAME = N'TODO\YourDbName-Copy_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [YourDbName] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [YourDbName].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [YourDbName] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [YourDbName] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [YourDbName] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [YourDbName] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [YourDbName] SET ARITHABORT OFF 
GO
ALTER DATABASE [YourDbName] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [YourDbName] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [YourDbName] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [YourDbName] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [YourDbName] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [YourDbName] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [YourDbName] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [YourDbName] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [YourDbName] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [YourDbName] SET  ENABLE_BROKER 
GO
ALTER DATABASE [YourDbName] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [YourDbName] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [YourDbName] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [YourDbName] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [YourDbName] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [YourDbName] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [YourDbName] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [YourDbName] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [YourDbName] SET  MULTI_USER 
GO
ALTER DATABASE [YourDbName] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [YourDbName] SET DB_CHAINING OFF 
GO
ALTER DATABASE [YourDbName] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [YourDbName] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [YourDbName] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [YourDbName] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [YourDbName] SET QUERY_STORE = OFF
GO
USE [YourDbName]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 01/12/2023 18:09:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Actions]    Script Date: 01/12/2023 18:09:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Actions](
	[Id] [smallint] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_Actions] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GlossaryItems]    Script Date: 01/12/2023 18:09:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GlossaryItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Term] [nvarchar](max) NOT NULL,
	[Definition] [nvarchar](max) NOT NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_GlossaryItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HistoryChanges]    Script Date: 01/12/2023 18:09:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HistoryChanges](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[GlossaryItemId] [int] NULL,
	[ActionId] [smallint] NULL,
	[DateOfChanges] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_HistoryChanges] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_HistoryChanges_ActionId]    Script Date: 01/12/2023 18:09:44 ******/
CREATE NONCLUSTERED INDEX [IX_HistoryChanges_ActionId] ON [dbo].[HistoryChanges]
(
	[ActionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HistoryChanges_GlossaryItemId]    Script Date: 01/12/2023 18:09:44 ******/
CREATE NONCLUSTERED INDEX [IX_HistoryChanges_GlossaryItemId] ON [dbo].[HistoryChanges]
(
	[GlossaryItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HistoryChanges]  WITH CHECK ADD  CONSTRAINT [FK_HistoryChanges_Actions_ActionId] FOREIGN KEY([ActionId])
REFERENCES [dbo].[Actions] ([Id])
GO
ALTER TABLE [dbo].[HistoryChanges] CHECK CONSTRAINT [FK_HistoryChanges_Actions_ActionId]
GO
ALTER TABLE [dbo].[HistoryChanges]  WITH CHECK ADD  CONSTRAINT [FK_HistoryChanges_GlossaryItems_GlossaryItemId] FOREIGN KEY([GlossaryItemId])
REFERENCES [dbo].[GlossaryItems] ([Id])
GO
ALTER TABLE [dbo].[HistoryChanges] CHECK CONSTRAINT [FK_HistoryChanges_GlossaryItems_GlossaryItemId]
GO
USE [master]
GO
ALTER DATABASE [YourDbName] SET  READ_WRITE 
GO
