// <auto-generated />
using System;
using DTI.Puzzle.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DTI.Puzzle.Persistence.Migrations
{
    [DbContext(typeof(GlossaryDbContext))]
    [Migration("20231127151210_20231127_Inital_Migration")]
    partial class _20231127_Inital_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DTI.Puzzle.Domain.Entities.Action", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Name = "Create"
                        },
                        new
                        {
                            Id = (short)2,
                            Name = "Update"
                        },
                        new
                        {
                            Id = (short)3,
                            Name = "Delete"
                        });
                });

            modelBuilder.Entity("DTI.Puzzle.Domain.Entities.DictionaryChangeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("ActionId")
                        .HasColumnType("smallint");

                    b.Property<int?>("GlossaryItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("GlossaryItemId");

                    b.ToTable("DictionaryChanges");
                });

            modelBuilder.Entity("DTI.Puzzle.Domain.Entities.GlossaryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GlossaryItems");
                });

            modelBuilder.Entity("DTI.Puzzle.Domain.Entities.DictionaryChangeHistory", b =>
                {
                    b.HasOne("DTI.Puzzle.Domain.Entities.Action", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId");

                    b.HasOne("DTI.Puzzle.Domain.Entities.GlossaryItem", "GlossaryItem")
                        .WithMany()
                        .HasForeignKey("GlossaryItemId");

                    b.Navigation("Action");

                    b.Navigation("GlossaryItem");
                });
#pragma warning restore 612, 618
        }
    }
}
